config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.FAIR:
    repos:
      this_repo:
        commands:
        - fair-eva.py -ID http://doi.org/10.5255/UKDA-SN-8231-1 -R oai-pmh -B http://digital.csic.es/dspace-oai/request
          --tool_endpoint https://datacatalogue.cessda.eu/oai-pmh/v0/oai
        container: qc.fair_flaky-carmine-numbat
timeout: 5400
